[workspace]
authors = ["David W.H. Swenson <dwhs@hyperblazer.net>"]
channels = ["conda-forge"]
name = "maintainer-for"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
requests = "*"
beautifulsoup4 = "*"
pytest = "*"
